import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rdot.in/public/login');
  await page.getByRole('textbox', { name: 'Company Name' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('VINODh');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('rsoft');
  await page.getByRole('textbox', { name: 'Enter Password' }).click();
  await page.getByRole('textbox', { name: 'Enter Password' }).fill('Vinodh@5292');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#vertical_header_name').click();
  await page.getByRole('link', { name: 'Contact_Mail Leads', exact: true }).click();
  await page.locator('.fa-solid.fa-envelope').first().click();
  await page.getByRole('textbox', { name: 'Select an Option', exact: true }).click();
  await page.getByRole('treeitem', { name: 'rsoftvinodh9@gmail.com' }).click();
  await page.getByRole('list').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('treeitem', { name: 'Primary Email ( Pradeep' }).click();
  await page.getByRole('list').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('treeitem', { name: 'Email (Leads)' }).click();
  await page.getByRole('list').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('treeitem', { name: 'Primary Email ( Pradeep' }).click();
  await page.getByRole('list').filter({ hasText: /^$/ }).click();
  await page.getByRole('treeitem', { name: 'Primary Email ( Pradeep' }).click();
  await page.locator('#select2-Emailvarfields-container').click();
  await page.getByRole('treeitem', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Select an option' }).click();
  await page.getByRole('treeitem', { name: 'Suresh' }).click();
  await page.locator('input[name="temp_sub"]').click();
  await page.locator('button').filter({ hasText: /^Save$/ }).click();
});